javascript:
  sources:
    - ./src/js/app.ts
  output:
    path: ./public/assets/js
    name: main.min.js
style:
  sources:
    - ./src/styles/style.scss
  output:
    path: ./public/assets/css
    name: style.min.css
browser_sync:
  proxy: localhost:8000
  browser: google chrome
  baseDir: ./
  files:
    - ./public/**/*
